# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20170919_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('ip', models.CharField(db_index=True, default='', max_length=255, verbose_name='ip')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Count vizits')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Platform', verbose_name='Platform')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Resouce', verbose_name='Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IpReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('date', models.DateTimeField(db_index=True, null=True, verbose_name='date')),
                ('user_agent', models.CharField(default='', max_length=255, verbose_name='user agent')),
                ('referer', models.CharField(default='', max_length=255, verbose_name='referer')),
                ('href', models.CharField(default='', max_length=255, verbose_name='href')),
                ('ip_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.IpReport', verbose_name='Ip report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('user', models.CharField(db_index=True, default='', max_length=255, verbose_name='user')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Count vizits')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Platform', verbose_name='Platform')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Resouce', verbose_name='Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('date', models.DateTimeField(db_index=True, null=True, verbose_name='date')),
                ('user_agent', models.CharField(default='', max_length=255, verbose_name='user agent')),
                ('referer', models.CharField(default='', max_length=255, verbose_name='referer')),
                ('href', models.CharField(default='', max_length=255, verbose_name='href')),
                ('ip', models.CharField(db_index=True, default='', max_length=255, verbose_name='ip')),
                ('user_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.UserReport', verbose_name='Ip report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
