# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20171010_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreportitem',
            name='distinct_ip',
        ),
        migrations.AddField(
            model_name='userreport',
            name='distinct_ip',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Distinct ip'),
        ),
    ]
