# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20171011_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipreportitem',
            name='user',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='user'),
        ),
    ]
