# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ipreportitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipreport',
            options={'ordering': ['-count']},
        ),
        migrations.AddField(
            model_name='userreport',
            name='user_agent',
            field=models.CharField(default='', max_length=255, verbose_name='user agent'),
        ),
    ]
