# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20171030_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipreport',
            name='distinct_cookie',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Distinct cookie'),
        ),
    ]
