# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resouce',
            name='pay_to',
            field=models.DateField(blank=True, null=True, verbose_name='Оплачен до '),
        ),
        migrations.AddField(
            model_name='resouce',
            name='watch',
            field=models.ManyToManyField(blank=True, to='customers.Platform', verbose_name='Отслеживаемый трафик'),
        ),
        migrations.AlterField(
            model_name='resouce',
            name='domain',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Domain'),
        ),
    ]
